name: Flutter CI/CD - Multi-Job Optimized

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# -------------------------------
# 1️⃣ Lint + Test Stage
# -------------------------------
jobs:
  analyze_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          cache: true
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test --no-pub

# -------------------------------
# 2️⃣ Android Build Stage
# -------------------------------
  build_android:
    needs: analyze_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          cache: true
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: flutter-apk-release
          path: build/app/outputs/flutter-apk/app-release.apk

# -------------------------------
# 3️⃣ Web Build + Deploy Stage
# -------------------------------
  build_web_deploy:
    needs: analyze_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          cache: true
      - run: flutter pub get
      - run: flutter build web --release --base-href="/"
      - uses: actions/upload-artifact@v4
        with:
          name: flutter-web-release
          path: build/web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          channelId: live